image_parameters:
  height_og: 720
  img_path: img/static_frame_from_video.jpg
  p1:
  - 76
  - 258
  p2:
  - 640
  - 242
  p3:
  - 54
  - 493
  p4:
  - 656
  - 493
  size_frame: '720'
  width_og: 576
